name: SkLogs
main: me.blueyescat.skriptlogs.SkriptLogs
description: An updated fork of Skript-logs
api-version: 1.13
version: @version@
author: [ ImNotStable, Equipable, Blueyescat ]
depend: [ Skript ]
website: https://github.com/EquipableMC/SkLogs