name: SkLogs
main: me.blueyescat.skriptlogs.SkLogs
description: An updated fork of Skript-logs
api-version: 1.13
version: @version@
authors: [Equipable, Blueyescat ]
depend: [ Skript ]
website: https://github.com/EquipableMC/SkLogs