name: SkLogs
description: An updated fork of Skript-logs
version: @version@

author: Equipable
website: https://github.com/EquipableMC/SkLogs

depend: [Skript]

main: me.blueyescat.skriptlogs.SkriptLogs
api-version: 1.13
